# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:2021.04

jobs:
  test-in-docker:
    executor: docker-executor
    steps:
      - checkout
      # Whatever you want to do
      - run: sudo apt-get update && sudo apt-get install -y tshark
      - run:
          name: "Setup PATH environment variable"
          command: export PATH=/usr/local/bin:$PATH
      - run:
          name: "Clone OMI data"
          command: git clone --depth=1 https://github.com/Open-Markets-Initiative/Data.git
      - run:
          name: "Running Tesh.sh"
          command: bash -x Test.sh

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  build-with-docker:
    # Run the welcome/run job in its own container
    jobs:
      - test-in-docker
